name: Node.js CI

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Setup Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - run: npm ci
    - name: Run build process(es)
      run: npm run build --if-present
    - name: Check Git status
      id: git
      shell: bash
      run: |
        RESULT=$(git status)
        if [[ $RESULT == *"Changes not staged"* || $RESULT == *"Untracked files"* ]]; then
          echo "Dirty working directory"
          exit 1
        fi
    - name: Comment on pull request
      if: failure()
      uses: actions/github-script@v4
      with:
        script: console.log(context)
