name: Node.js CI

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Setup Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - run: npm ci
    - run: npm run build --if-present
    - run: git diff
